token: ""

guild_id: 123456789

log_level: "INFO"

base_voice: "Voice"

owner_id: 164546159140929538

discord_bots_key: 123456

postgres_credentials:
    host: "postgres-db"
    user: "yinbotuser"
    database: "yinbotdb"
    password: "yinbot-password"

prod: false

cogs:
    - Admin
    - Autoassign
    - Filter
    - Gateway
    - Info
    - Logging
    - Moderation
    - Owner
    - Pings
    - Rng
    - Roles
    - Stats
    - Voice
    - Warnings
